# Generated by Django 4.2 on 2023-04-26 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("contato", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("bebidas", "Bebidas"),
                            ("alimentos", "Alimentos"),
                            ("kits", "Kits"),
                            ("utensílios", "Utensílios"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PontodeVenda.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vendas",
            },
        ),
        migrations.CreateModel(
            name="Venda_de_Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_vendida", models.PositiveIntegerField()),
                (
                    "produtos_para_venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PontodeVenda.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PontodeVenda.venda",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Realizar Vendas",
            },
        ),
        migrations.AddField(
            model_name="venda",
            name="produtos",
            field=models.ManyToManyField(
                through="PontodeVenda.Venda_de_Produto", to="PontodeVenda.produto"
            ),
        ),
    ]
