# Generated by Django 4.2 on 2023-05-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PontodeVenda', '0006_alter_vendaproduto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
