# Generated by Django 4.2 on 2023-04-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PontodeVenda", "0002_rename_venda_de_produto_vendaproduto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendaproduto",
            old_name="produtos",
            new_name="produtos_para_venda",
        ),
    ]
