# Generated by Django 4.2 on 2023-04-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PontodeVenda", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Venda_de_Produto",
            new_name="VendaProduto",
        ),
        migrations.AlterModelOptions(
            name="venda",
            options={},
        ),
        migrations.RenameField(
            model_name="vendaproduto",
            old_name="produtos_para_venda",
            new_name="produtos",
        ),
    ]
