# Generated by Django 4.2 on 2023-04-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PontodeVenda", "0003_rename_produtos_vendaproduto_produtos_para_venda"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venda",
            options={"verbose_name_plural": "Vendas"},
        ),
        migrations.AlterModelOptions(
            name="vendaproduto",
            options={},
        ),
        migrations.RenameField(
            model_name="vendaproduto",
            old_name="produtos_para_venda",
            new_name="produto",
        ),
        migrations.RenameField(
            model_name="vendaproduto",
            old_name="quantidade_vendida",
            new_name="quantidade",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="produtos",
        ),
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
